# Generated by Django 3.0.8 on 2020-10-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=254)),
                ('sealed', models.BooleanField(help_text="Only tick this box if your game is still contained in it's original wrapping")),
                ('condition', models.CharField(choices=[('perfect,', 'PERFECT'), ('good', 'GOOD'), ('well used', 'WELL USED'), ('damaged', 'DAMAGED')], default='good', max_length=25)),
            ],
        ),
    ]
