# Generated by Django 3.0.8 on 2020-11-27 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0003_auto_20201124_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='model_pic',
            field=models.ImageField(default='', null=True, upload_to='user_game_images/'),
        ),
    ]
