# Generated by Django 3.0.8 on 2020-11-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0004_auto_20201127_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='model_pic',
        ),
        migrations.AlterField(
            model_name='game',
            name='game_description',
            field=models.TextField(blank=True, default='Please disclose any damage, defects, and/or missing pieces', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='sealed',
            field=models.BooleanField(null=True),
        ),
    ]
