# Generated by Django 3.0.8 on 2020-11-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0005_auto_20201128_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='model_pic',
            field=models.ImageField(default='', null=True, upload_to='static/images/user_game_images/'),
        ),
    ]
