# Generated by Django 3.0.8 on 2020-11-28 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0006_game_model_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='model_pic',
        ),
    ]
