# Generated by Django 3.0.8 on 2020-11-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0007_remove_game_model_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='email',
            field=models.EmailField(default='Please enter your email address', max_length=254),
            preserve_default=False,
        ),
    ]
