# Generated by Django 3.0.8 on 2020-11-30 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0008_game_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_description',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
    ]
