# Generated by Django 3.0.8 on 2020-11-09 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_players', models.IntegerField(default=0.0)),
                ('max_players', models.IntegerField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('sku', models.CharField(blank=True, max_length=254, null=True)),
                ('primary_publisher', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('description_preview', models.CharField(blank=True, max_length=512, null=True)),
                ('year_published', models.IntegerField()),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('thumb_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('url', models.URLField(blank=True, max_length=1024, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('msrp', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Age')),
                ('players', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Players')),
            ],
        ),
    ]
