# Generated by Django 3.0.8 on 2020-08-21 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='publishers',
            new_name='primary_publisher',
        ),
    ]
