# Generated by Django 3.0.8 on 2020-11-10 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='age',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Age'),
        ),
        migrations.AlterField(
            model_name='product',
            name='players',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Players'),
        ),
    ]
