# Generated by Django 3.0.8 on 2020-08-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200821_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_preview',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='max_playtime',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='mechanics',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='min_age',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='min_players',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='min_playtime',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='publishers',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='thumb_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_players',
            field=models.IntegerField(default=0.0),
        ),
    ]
