# Generated by Django 3.0.8 on 2020-08-22 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='publishers',
        ),
        migrations.AlterField(
            model_name='product',
            name='min_age',
            field=models.IntegerField(),
        ),
    ]
